name: ccwav
on:
  schedule:
    - cron: '30 23 * * *'
  workflow_dispatch:
  watch:
    types: started
  repository_dispatch:
    types: ccwav-QLScript
jobs:
  repo-sync:
    env:
      PAT: ${{ secrets.PAT }} 
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: sync ccwav-QLScript
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/gcdd1993/My-Scripts.git"
          source_branch: "ccwav"
          destination_branch: "ccwav"
          github_token: ${{ secrets.PAT }}
