name: CenBoMin-JDTASK_V2P
on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:
  watch:
    types: started
  repository_dispatch:
    types: CenBoMin-JDTASK_V2P
jobs:
  repo-sync:
    env:
      PAT: ${{ secrets.PAT }} 
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: sync CenBoMin-JDTASK_V2P
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/CenBoMin/JDTASK_V2P.git"
          source_branch: "main"
          destination_branch: "CenBoMin-JDTASK_V2P"
          github_token: ${{ secrets.PAT }}
