name: Kedaya
on:
  schedule:
    - cron: '0 0,12 * * *'
  workflow_dispatch:
  watch:
    types: started
  repository_dispatch:
    types: qitoqito-kedaya
jobs:
  repo-sync:
    env:
      PAT: ${{ secrets.PAT }} 
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: sync qitoqito-kedaya
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/qitoqito/kedaya.git"
          source_branch: "main"
          destination_branch: "Kedaya"
          github_token: ${{ secrets.PAT }}
