name: LXK-JD
on:
  schedule:
    - cron: '30 23 * * *'
  workflow_dispatch:
  watch:
    types: started
  repository_dispatch:
    types: Aaron-lv-sync
jobs:
  repo-sync:
    env:
      PAT: ${{ secrets.PAT }} 
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: sync Aaron-lv-sync
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/Aaron-lv/sync.git"
          source_branch: "jd_scripts"
          destination_branch: "LXK-JD"
          github_token: ${{ secrets.PAT }}
